### PR TITLE
Add `.adr` directory and flowchart/statechart doc

### PR DESCRIPTION
**Pull request by NiloCK**
credit to @geoknee, whose work I have shamelessly rearranged in order to up my commit count.

Adapted from original PR:

> 
> This PR adds an architectural decision record ([preview here!](https://github.com/statechannels/go-nitro/tree/adr-directory/protocols/.adr)).
> 
> The architectural decision record (ADR) is in a hidden folder, and contains much more information about why we went with the current design. It contains discarded code -- but I chose to embed this in markdown to remove any confusion about it forming a functional part of the codebase. It is information only.  See @NiloCK's [pitch](https://www.notion.so/statechannels/Store-Finalized-ADRs-in-their-respective-Repository-ies-b4851f8e1d2a4b629ece64b69daa6a9a).
> 
> The ADR is experimental, and generally a bit rougher as a document. I don't want to spend a lot of time polishing it up, so if it proves controversial we can just drop it for now.

~**TODO**: the readme from the original PR no longer contains a back-link to the adr directory. If this is merged, that link should be re-inserted.~

### CODE REVIEW

**Comment by geoknee** [comment]
@NiloCK:
I have
* merged #59 into main
* rebase this branch onto main
* reinstated the link from the readme

**Review by andrewgordstewart — COMMENTED** [review]
[accidental review due to malfunctioning keyboard]

**Comment by andrewgordstewart** [comment]
I enthusiastically support including ADRs in our repo. My concerns with this PR are:

1. the content of this ADR has a lot of meat to it -- it's hard to know how intelligible it would be to "future peers" (see https://github.blog/2020-08-13-why-write-adrs/) because of the various jargon used. Words like reducer, extended state, state chart, context are meaningful to us thanks to a couple of years of using them.
2. the structure of this ADR (and its peer in #143) is dissimilar to the types of structure I frequently see in the literature (see [ref 1](https://github.com/joelparkerhenderson/architecture-decision-record#suggestions-for-writing-good-adrs) or [ref 2](https://adr.github.io/#sustainable-architectural-decisions))
3. this PR endorses creating many `.adr` folders. can you explain why this is preferred to a single `.adr` folder?

This specific ADR could benefit from being distilled into a "lightweight ADR" adhering to a rough, agreed-upon format. The "meat" of this PR can be included as expanded, supporting context. This would address concerns 1 & 2.

**Comment by andrewgordstewart** [comment]
After we address concern (3), I'm inclined to suggest
1. merging this PR to get its content recorded in git
2. addressing concerns 1 & 2 by replacing it with a more digestible ADR, and moving this content to a supporting file

thoughts?

**Pull request merged**
